# Generated by Django 5.0.1 on 2026-04-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='SBERT semantic similarity score (0-100)')),
                ('contextual_score', models.FloatField(help_text='GPT contextual evaluation score (0-100)')),
                ('final_score', models.FloatField(help_text='Weighted final score (0-100)')),
                ('overall_feedback', models.TextField(help_text='Overall evaluation feedback')),
                ('evaluation_metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the evaluation process')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'db_table': 'evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='SBERT similarity score for this question (0-100)')),
                ('contextual_score', models.FloatField(help_text='GPT contextual score for this question (0-100)')),
                ('final_score', models.FloatField(help_text='Weighted final score for this question (0-100)')),
                ('feedback', models.TextField(help_text='Detailed feedback for this answer')),
                ('strengths', models.JSONField(blank=True, default=list, help_text='List of strengths identified in the answer')),
                ('weaknesses', models.JSONField(blank=True, default=list, help_text='List of weaknesses/areas for improvement')),
                ('suggestions', models.TextField(blank=True, help_text='Suggestions for improvement')),
                ('completeness', models.FloatField(blank=True, help_text='How complete is the answer (0-100)', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='How accurate is the answer (0-100)', null=True)),
                ('clarity', models.FloatField(blank=True, help_text='How clear is the answer (0-100)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question Evaluation',
                'verbose_name_plural': 'Question Evaluations',
                'db_table': 'question_evaluations',
                'ordering': ['evaluation', 'question__question_number'],
            },
        ),
    ]
