# Generated by Django 5.0.1 on 2026-04-06 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='exam',
            field=models.OneToOneField(help_text='Associated exam', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='questionevaluation',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_evaluations', to='evaluations.evaluation'),
        ),
        migrations.AddField(
            model_name='questionevaluation',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_result', to='exams.questionanswer'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['-created_at'], name='evaluations_created_2b4202_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['final_score'], name='evaluations_final_s_104889_idx'),
        ),
    ]
