# Generated by Django 5.0.1 on 2026-04-06 11:38

import django.core.validators
import exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded exam file', upload_to=exams.models.exam_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'jpg', 'jpeg', 'png'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('raw_text', models.TextField(blank=True, help_text='Extracted text from file')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('is_guest', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exams',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('student_answer', models.TextField()),
                ('model_answer', models.TextField(help_text='Expected/correct answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question Answer',
                'verbose_name_plural': 'Question Answers',
                'db_table': 'question_answers',
                'ordering': ['exam', 'question_number'],
            },
        ),
    ]
