# Generated by Django 5.0.1 on 2026-04-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(blank=True, help_text='Total marks for the exam', null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='marks',
            field=models.IntegerField(blank=True, help_text='Marks allocated for this question', null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='obtained_marks',
            field=models.FloatField(blank=True, help_text='Marks obtained for this question after evaluation', null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='Multiple choice options if applicable', null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question_type',
            field=models.CharField(default='short_answer', help_text='Type of question: essay, multiple_choice, short_answer, fill_blank', max_length=50),
        ),
    ]
